# clang LTO
/CONFIG_LTO_NONE.*$/d;
$ a CONFIG_LTO_CLANG_THIN=y
$ a CONFIG_LTO=y
$ a CONFIG_HAS_LTO_CLANG=y
$ a CONFIG_LTO_CLANG=y
# Build for Ryzen 5
# Not yet supported.
# s/^(CONFIG_MZEN3=.*|# CONFIG_MZEN3 is not set)/CONFIG_MZEN3=y/;
s/^(CONFIG_MNATIVE_AMD=.*|# CONFIG_MNATIVE_AMD is not set)/CONFIG_MNATIVE_AMD=y/;
s/^CONFIG_GENERIC_CPU=.*/# CONFIG_GENERIC_CPU is not set/;
# FS
s/^(CONFIG_EXT4_FS=.*|# CONFIG_EXT4_FS is not set)/CONFIG_EXT4_FS=y/;
s/^(CONFIG_BTRFS_FS=.*|# CONFIG_BTRFS_FS is not set)/CONFIG_BTRFS_FS=y/;
#
# ZRAM
s/^(CONFIG_ZBUD=.*|# CONFIG_ZBUD is not set)/CONFIG_ZBUD=y/;
s/^(CONFIG_ZSMALLOC=.*|# CONFIG_ZSMALLOC is not set)/CONFIG_ZSMALLOC=y/;
#
# Hardware acceleration for btrfs checksums
s/^(CONFIG_CRYPTO_CRC32C=.*|# CONFIG_CRYPTO_CRC32C is not set)/CONFIG_CRYPTO_CRC32C=y/;
s/^(CONFIG_CRYPTO_CRC32C_INTEL=.*|# CONFIG_CRYPTO_CRC32C_INTEL is not set)/CONFIG_CRYPTO_CRC32C_INTEL=y/;
#
# Allow to override ACPI Rev (useful for xps 15 9560)
s/^(CONFIG_ACPI_REV_OVERRIDE_POSSIBLE=.*|# CONFIG_ACPI_REV_OVERRIDE_POSSIBLE is not set)/CONFIG_ACPI_REV_OVERRIDE_POSSIBLE=y/;
#
# ZSTD compression
s/^CONFIG_KERNEL_XZ=.*/# CONFIG_KERNEL_XZ is not set/;
s/^(CONFIG_KERNEL_ZSTD=.*|# CONFIG_KERNEL_ZSTD is not set)/CONFIG_KERNEL_ZSTD=y/;
s/^(CONFIG_MODULE_COMPRESS=.*|# CONFIG_MODULE_COMPRESS is not set)/CONFIG_MODULE_COMPRESS=y/;
$ a CONFIG_MODULE_COMPRESS_ZSTD=y
#
# Enable PSI per default
s/^(CONFIG_PSI_DEFAULT_DISABLED=.*|# CONFIG_PSI_DEFAULT_DISABLED is not set)/CONFIG_PSI_DEFAULT_DISABLED=n/;
#
# Enable MGEN LRU
s/^(CONFIG_LRU_GEN_ENABLED=.*|# CONFIG_LRU_GEN_ENABLED is not set)/CONFIG_LRU_GEN_ENABLED=y/;
#
#
# AHCI
s/^(CONFIG_SATA_AHCI=.*|# CONFIG_SATA_AHCI is not set)/CONFIG_SATA_AHCI=y/;
# AMD (ryzen) CPU
s/^(CONFIG_AMD_IOMMU=.*|# CONFIG_AMD_IOMMU is not set)/CONFIG_AMD_IOMMU=y/;
# Include AMDGPU
s/^(CONFIG_DRM_AMDGPU=.*|# CONFIG_DRM_AMDGPU is not set)/CONFIG_DRM_AMDGPU=y/;
s/^CONFIG_DRM_RADEON=.*/# CONFIG_DRM_RADEON is not set/;
s/^CONFIG_FB_RADEON=.*/# CONFIG_FB_RADEON is not set/;
s/^CONFIG_FB_ATY128=.*/# CONFIG_FB_ATY128 is not set/;
s/^CONFIG_FB_ATY=.*/# CONFIG_FB_ATY is not set/;
# NFS
s/^(CONFIG_NFS_V4=.*|# CONFIG_NFS_V4 is not set)/CONFIG_NFS_V4=y/;
# Mellanox
s/^(CONFIG_NET_VENDOR_MELLANOX=.*|# CONFIG_NET_VENDOR_MELLANOX is not set)/CONFIG_NET_VENDOR_MELLANOX=y/;
s/^(CONFIG_MLX4_CORE_GEN2=.*|# CONFIG_MLX4_CORE_GEN2 is not set)/CONFIG_MLX4_CORE_GEN2=y/;
# NVME
s/^(CONFIG_NVME_CORE=.*|# CONFIG_NVME_CORE is not set)/CONFIG_NVME_CORE=y/;
s/^(CONFIG_BLK_DEV_NVME=.*|# CONFIG_BLK_DEV_NVME is not set)/CONFIG_BLK_DEV_NVME=y/;

# Cleaning
s/^(CONFIG_CDROM=.*|# CONFIG_CDROM is not set)/CONFIG_CDROM=m/;
s/^(CONFIG_BLK_DEV_SR=.*|# CONFIG_BLK_DEV_SR is not set)/CONFIG_BLK_DEV_SR=m/;
s/^(CONFIG_CHR_DEV_SG=.*|# CONFIG_CHR_DEV_SG is not set)/CONFIG_CHR_DEV_SG=m/;
s/^(CONFIG_ATA_PIIX=.*|# CONFIG_ATA_PIIX is not set)/CONFIG_ATA_PIIX=m/;
s/^(CONFIG_PATA_SIS=.*|# CONFIG_PATA_SIS is not set)/CONFIG_PATA_SIS=m/;
s/^(CONFIG_BLK_DEV_MD=.*|# CONFIG_BLK_DEV_MD is not set)/CONFIG_BLK_DEV_MD=m/;
s/^(CONFIG_BLK_DEV_DM=.*|# CONFIG_BLK_DEV_DM is not set)/CONFIG_BLK_DEV_DM=m/;
s/^(CONFIG_FDDI=.*|# CONFIG_FDDI is not set)/CONFIG_FDDI=m/;
s/^(CONFIG_MDIO_DEVICE=.*|# CONFIG_MDIO_DEVICE is not set)/CONFIG_MDIO_DEVICE=m/;
s/^(CONFIG_MDIO_BUS=.*|# CONFIG_MDIO_BUS is not set)/CONFIG_MDIO_BUS=m/;
s/^(CONFIG_MDIO_DEVRES=.*|# CONFIG_MDIO_DEVRES is not set)/CONFIG_MDIO_DEVRES=m/;
s/^(CONFIG_PHYLIB=.*|# CONFIG_PHYLIB is not set)/CONFIG_PHYLIB=m/;
s/^(CONFIG_SERIO=.*|# CONFIG_SERIO is not set)/CONFIG_SERIO=m/;
s/^(CONFIG_AGP=.*|# CONFIG_AGP is not set)/CONFIG_AGP=m/;
s/^(CONFIG_AGP_AMD64=.*|# CONFIG_AGP_AMD64 is not set)/CONFIG_AGP_AMD64=m/;
s/^(CONFIG_AGP_INTEL=.*|# CONFIG_AGP_INTEL is not set)/CONFIG_AGP_INTEL=m/;
s/^(CONFIG_MMC=.*|# CONFIG_MMC is not set)/CONFIG_MMC=m/;
s/^(CONFIG_VFIO=.*|# CONFIG_VFIO is not set)/CONFIG_VFIO=m/;
s/^CONFIG_X86_MCELOG_LEGACY=.*/# CONFIG_X86_MCELOG_LEGACY is not set/;
s/^(CONFIG_X86_PCC_CPUFREQ=.*|# CONFIG_X86_PCC_CPUFREQ is not set)/CONFIG_X86_PCC_CPUFREQ=m/;
s/^(CONFIG_X86_POWERNOW_K8=.*|# CONFIG_X86_POWERNOW_K8 is not set)/CONFIG_X86_POWERNOW_K8=m/;
s/^(CONFIG_ISA_BUS=.*|# CONFIG_ISA_BUS is not set)/CONFIG_ISA_BUS=m/;
s/^(CONFIG_EFI_TEST=.*|# CONFIG_EFI_TEST is not set)/CONFIG_EFI_TEST=m/;
s/^(CONFIG_DNS_RESOLVER=.*|# CONFIG_DNS_RESOLVER is not set)/CONFIG_DNS_RESOLVER=m/;
s/^(CONFIG_RFKILL=.*|# CONFIG_RFKILL is not set)/CONFIG_RFKILL=m/;
s/^(CONFIG_CAIF=.*|# CONFIG_CAIF is not set)/CONFIG_CAIF=m/;
s/^CONFIG_PCI_ENDPOINT=.*/# CONFIG_PCI_ENDPOINT is not set/;
/^CONFIG_RAPIDIO/d;
s/^CONFIG_UEVENT_HELPER=.*/# CONFIG_UEVENT_HELPER is not set/;
/^CONFIG_UEVENT_HELPER_PATH/d;
s/^CONFIG_MTD_UBI_FASTMAP=.*/# CONFIG_MTD_UBI_FASTMAP is not set/;
s/^CONFIG_MTD_UBI_BLOCK=.*/# CONFIG_MTD_UBI_BLOCK is not set/;
s/^CONFIG_PARIDE=.*/# CONFIG_PARIDE is not set/;
/^CONFIG_PARIDE_/d;
s/^(CONFIG_XEN_BLKDEV_FRONTEND=.*|# CONFIG_XEN_BLKDEV_FRONTEND is not set)/CONFIG_CAIF=m/;
s/^CONFIG_SRAM=.*/# CONFIG_SRAM is not set/;
s/^CONFIG_SATA_DWC_OLD_DMA=.*/# CONFIG_SATA_DWC_OLD_DMA is not set/;
s/^(CONFIG_ATA_GENERIC=.*|# CONFIG_ATA_GENERIC is not set)/CONFIG_ATA_GENERIC=m/;
s/^(CONFIG_TUN=.*|# CONFIG_TUN is not set)/CONFIG_TUN=m/;
s/^CONFIG_ARCNET=.*/# CONFIG_ARCNET is not set/;
/^CONFIG_ARCNET_/d;
/^CONFIG_CAIF_/d;
s/^(CONFIG_BCM84881_PHY=.*|# CONFIG_BCM84881_PHY is not set)/CONFIG_BCM84881_PHY=m/;
s/^(CONFIG_PPP=.*|# CONFIG_PPP is not set)/CONFIG_PPP=m/;
s/^(CONFIG_SLHC=.*|# CONFIG_SLHC is not set)/CONFIG_SLHC=m/;
s/^CONFIG_WAN=.*/# CONFIG_WAN is not set/;
s/^(CONFIG_TOUCHSCREEN_ELAN=.*|# CONFIG_TOUCHSCREEN_ELAN is not set)/CONFIG_TOUCHSCREEN_ELAN=m/;
s/^(CONFIG_SERIAL_KGDB_NMI=.*|# CONFIG_SERIAL_KGDB_NMI is not set)/CONFIG_SERIAL_KGDB_NMI=m/;
/^CONFIG_SERIAL_KGDB_NMI/d;
/^CONFIG_CONSOLE_POLL/d;
s/^CONFIG_I3C=.*/# CONFIG_I3C is not set/;
s/^CONFIG_SPMI=.*/# CONFIG_SPMI is not set/;
s/^CONFIG_HSI=.*/# CONFIG_HSI is not set/;
s/^(CONFIG_GPIO_XILINX=.*|# CONFIG_GPIO_XILINX is not set)/CONFIG_GPIO_XILINX=m/;
s/^(CONFIG_GPIO_CRYSTAL_COVE=.*|# CONFIG_GPIO_CRYSTAL_COVE is not set)/CONFIG_GPIO_CRYSTAL_COVE=m/;
/^CONFIG_VIDEO_ADV/d;
s/^(CONFIG_AGP_VIA=.*|# CONFIG_AGP_VIA is not set)/CONFIG_AGP_VIA=m/;
s/^(CONFIG_INTEL_GTT=.*|# CONFIG_INTEL_GTT is not set)/CONFIG_INTEL_GTT=m/;
/^CONFIG_COMEDI/d;
/^CONFIG_FB_TFT/d;
/^CONFIG_GREYBUS/d;
/^CONFIG_ANDROID/d;
/^CONFIG_KGDB/d;
s/^CONFIG_FTRACE=.*/# CONFIG_FTRACE is not set/;
s/^CONFIG_SAMPLES=.*/# CONFIG_SAMPLES is not set/;
